### ISSUE TITLE
Inconsistency with httpResponse.code

### ISSUE THREAD

**Issue by hongkongkiwi** [horpto/nodecap2#3]
When checking the httpResponse object in a 'request' type, the httpResponse.code is a number (200).

When checking the httpResponse object in a 'response' type, the httpResponse.code is a string '200'.

This causes a slight issue when using the same filter for both request & response.

**Comment by horpto** [comment]
Hm, you right, change type of httpResponse.code to Number, but I change version from 0.2 to 2.0 as it's incompatible with current version (0.2).
now, you can download nodecap2 with tag 'next'
